
-- Tabla CIUDAD
CREATE TABLE CIUDAD (
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL
);

-- Tabla USUARIO_CONDUCTOR
CREATE TABLE USUARIO_CONDUCTOR (
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    cedula VARCHAR2(20) NOT NULL UNIQUE,
    nombre VARCHAR2(100) NOT NULL,
    correo VARCHAR2(100) NOT NULL UNIQUE,
    celular VARCHAR2(20) NOT NULL,
    calificacion NUMBER DEFAULT 0 CHECK (calificacion >= 0 AND calificacion <= 5)
);

ALTER TABLE USUARIO_CONDUCTOR ADD estado VARCHAR2(20) DEFAULT 'DISPONIBLE';

UPDATE USUARIO_CONDUCTOR SET estado = 'DISPONIBLE';

COMMIT;

-- Tabla USUARIO_SERVICIO
CREATE TABLE USUARIO_SERVICIO (
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    cedula VARCHAR2(20) NOT NULL UNIQUE,
    nombre VARCHAR2(100) NOT NULL,
    correo VARCHAR2(100) NOT NULL UNIQUE,
    celular VARCHAR2(20) NOT NULL,
    calificacion NUMBER DEFAULT 0 CHECK (calificacion >= 0 AND calificacion <= 5),
    numTarjeta VARCHAR2(20),
    nombreTarjeta VARCHAR2(100),
    vencimiento VARCHAR2(10),
    codigoSeguridad NUMBER
);

-- Tabla VEHICULO
CREATE TABLE VEHICULO (
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    placa VARCHAR2(10) NOT NULL UNIQUE,
    marca VARCHAR2(50) NOT NULL,
    modelo VARCHAR2(50) NOT NULL,
    capacidadPasajeros NUMBER NOT NULL CHECK (capacidadPasajeros > 0),
    nivel VARCHAR2(20) CHECK (nivel IN ('LARGE', 'COMFORT', 'ESTANDAR')),
    id_usuarioConductor NUMBER NOT NULL,
    CONSTRAINT fk_vehiculo_conductor FOREIGN KEY (id_usuarioConductor) 
        REFERENCES USUARIO_CONDUCTOR(id) ON DELETE CASCADE
);

-- Tabla SERVICIO
CREATE TABLE SERVICIO (
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    distanciaKm NUMBER,
    idTarifa NUMBER,
    tipoServicio VARCHAR2(50) NOT NULL,
    fecha DATE NOT NULL,
    costo NUMBER(10,2) NOT NULL,
    id_usuarioConductor NUMBER NOT NULL,
    id_usuarioServicio NUMBER NOT NULL,
    id_vehiculo NUMBER NOT NULL,
    CONSTRAINT fk_servicio_conductor FOREIGN KEY (id_usuarioConductor) 
        REFERENCES USUARIO_CONDUCTOR(id) ON DELETE CASCADE,
    CONSTRAINT fk_servicio_usuario FOREIGN KEY (id_usuarioServicio) 
        REFERENCES USUARIO_SERVICIO(id) ON DELETE CASCADE,
    CONSTRAINT fk_servicio_vehiculo FOREIGN KEY (id_vehiculo) 
        REFERENCES VEHICULO(id) ON DELETE CASCADE
);

-- Tabla PUNTO
CREATE TABLE PUNTO (
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    direccion VARCHAR2(200) NOT NULL,
    longitud NUMBER NOT NULL,
    latitud NUMBER NOT NULL,
    orden NUMBER NOT NULL,
    id_servicio NUMBER NOT NULL,
    id_ciudad NUMBER NOT NULL,
    CONSTRAINT fk_punto_servicio FOREIGN KEY (id_servicio) 
        REFERENCES SERVICIO(id) ON DELETE CASCADE,
    CONSTRAINT fk_punto_ciudad FOREIGN KEY (id_ciudad) 
        REFERENCES CIUDAD(id) ON DELETE CASCADE
);

-- Tabla REVISION
CREATE TABLE REVISION (
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    calificacion NUMBER NOT NULL CHECK (calificacion >= 1 AND calificacion <= 5),
    comentario VARCHAR2(200) NOT NULL,
    id_servicio NUMBER NOT NULL,
    CONSTRAINT fk_revision_servicio FOREIGN KEY (id_servicio) 
        REFERENCES SERVICIO(id) ON DELETE CASCADE
);

-- Tabla VIAJE
CREATE TABLE VIAJE (
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    horaInicio VARCHAR2(10),
    horaFin VARCHAR2(10),
    costo NUMBER(10,2) NOT NULL,
    id_servicio NUMBER NOT NULL,
    CONSTRAINT fk_viaje_servicio FOREIGN KEY (id_servicio) 
        REFERENCES SERVICIO(id) ON DELETE CASCADE
);

-- ====================================
-- ÍNDICES PARA MEJORAR PERFORMANCE
-- ====================================
CREATE INDEX idx_vehiculo_conductor ON VEHICULO(id_usuarioConductor);
CREATE INDEX idx_servicio_conductor ON SERVICIO(id_usuarioConductor);
CREATE INDEX idx_servicio_usuario ON SERVICIO(id_usuarioServicio);
CREATE INDEX idx_servicio_vehiculo ON SERVICIO(id_vehiculo);
CREATE INDEX idx_servicio_fecha ON SERVICIO(fecha);
CREATE INDEX idx_punto_servicio ON PUNTO(id_servicio);
CREATE INDEX idx_punto_ciudad ON PUNTO(id_ciudad);
CREATE INDEX idx_revision_servicio ON REVISION(id_servicio);
CREATE INDEX idx_viaje_servicio ON VIAJE(id_servicio);


SELECT column_name 
FROM user_tab_columns 
WHERE table_name = 'USUARIO_CONDUCTOR'
ORDER BY column_id;

DESC USUARIO_SERVICIO;

SELECT object_type 
FROM user_objects 
WHERE object_name = 'USUARIO_SERVICIO';

SELECT constraint_name, column_name
FROM user_cons_columns
WHERE table_name = 'USUARIO_CONDUCTOR'
AND constraint_name IN (
    SELECT constraint_name
    FROM user_constraints
    WHERE constraint_type='P'
);

-- Oracle no soporta IF EXISTS en DROP TABLE directamente
-- Tampoco tiene FOREIGN_KEY_CHECKS como MySQL

-- Opción 1: DROP con CASCADE CONSTRAINTS (recomendada)
DROP TABLE BARES CASCADE CONSTRAINTS;
DROP TABLE CIUDAD CASCADE CONSTRAINTS;
DROP TABLE DIA CASCADE CONSTRAINTS;
DROP TABLE DISPONIBILIDAD CASCADE CONSTRAINTS;
DROP TABLE HORA CASCADE CONSTRAINTS;
DROP TABLE PUNTO CASCADE CONSTRAINTS;
DROP TABLE RESERVAS CASCADE CONSTRAINTS;
DROP TABLE REVISION CASCADE CONSTRAINTS;
DROP TABLE SERVICIO CASCADE CONSTRAINTS;
DROP TABLE SILLASRESERVAS CASCADE CONSTRAINTS;
DROP TABLE TARIFA CASCADE CONSTRAINTS;
DROP TABLE USUARIO CASCADE CONSTRAINTS;
DROP TABLE USUARIO_CONDUCTOR CASCADE CONSTRAINTS;
DROP TABLE USUARIO_SERVICIO CASCADE CONSTRAINTS;
DROP TABLE VEHICULO CASCADE CONSTRAINTS;
DROP TABLE VIAJE CASCADE CONSTRAINTS;

COMMIT;

SELECT COLUMN_NAME, GENERATION_TYPE
FROM USER_TAB_IDENTITY_COLS
WHERE TABLE_NAME = 'SERVICIO';